# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the . package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: .\n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: attranslate\n"
# 
# File: usr/share/build-package/github_api.py, line: 29
# File: usr/share/build-package/github_api.py, line: 73
# File: usr/share/build-package/github_api.py, line: 342
# File: usr/share/build-package/github_api.py, line: 391
#: NEEDS WORK
msgid "Could not determine repository name."
msgstr "Nelze určit název repozitáře."
# 
# File: usr/share/build-package/github_api.py, line: 35
#: NEEDS WORK
msgid "Could not determine current commit SHA."
msgstr "Nelze určit aktuální SHA commitu."
# 
# File: usr/share/build-package/github_api.py, line: 44
#: NEEDS WORK
#, python-brace-format
msgid "Creating reference: {0}..."
msgstr "Vytváření reference: {0}..."
# 
# File: usr/share/build-package/github_api.py, line: 59
# File: usr/share/build-package/github_api.py, line: 65
#: NEEDS WORK
#, python-brace-format
msgid "Error creating reference: {0}"
msgstr "Chyba při vytváření odkazu: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 62
#: NEEDS WORK
#, python-brace-format
msgid "Reference {0} created successfully!"
msgstr "Reference {0} byla úspěšně vytvořena!"
# 
# File: usr/share/build-package/github_api.py, line: 86
#: NEEDS WORK
#, python-brace-format
msgid "Could not determine SHA for {0}."
msgstr "Nelze určit SHA pro {0}."
# 
# File: usr/share/build-package/github_api.py, line: 89
#: NEEDS WORK
#, python-brace-format
msgid "Creating branch: {0} based on {1}..."
msgstr "Vytváření větve: {0} na základě {1}..."
# 
# File: usr/share/build-package/github_api.py, line: 101
# File: usr/share/build-package/github_api.py, line: 166
#: NEEDS WORK
#, python-brace-format
msgid "Error creating branch: {0}"
msgstr "Chyba při vytváření větve: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 102
# File: usr/share/build-package/github_api.py, line: 478
#: NEEDS WORK
#, python-brace-format
msgid "Error details: {0}"
msgstr "Podrobnosti o chybě: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 160
#: NEEDS WORK
#, python-brace-format
msgid "Warning: Could not mark branch as non-PR: {0}"
msgstr "Upozornění: Nelze označit větev jako non-PR: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 163
#: NEEDS WORK
#, python-brace-format
msgid "Branch {0} created successfully!"
msgstr "Větev {0} byla úspěšně vytvořena!"
# 
# File: usr/share/build-package/github_api.py, line: 240
#: NEEDS WORK
msgid "Failed to create branch for the build."
msgstr "Nepodařilo se vytvořit větev pro sestavení."
# 
# File: usr/share/build-package/github_api.py, line: 245
#: NEEDS WORK
#, python-brace-format
msgid "Using existing branch: {0}"
msgstr "Používání stávající větve: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 267
#: NEEDS WORK
#, python-brace-format
msgid "Error retrieving remote repository URL for package: {0}"
msgstr "Chyba při získávání URL vzdáleného repozitáře pro balíček: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 270
#: NEEDS WORK
#, python-brace-format
msgid "Detected repository: {0}"
msgstr "Zjištěné úložiště: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 285
#: NEEDS WORK
msgid "Triggering build workflow on GitHub..."
msgstr "Spouštění pracovního postupu sestavení na GitHubu..."
# 
# File: usr/share/build-package/github_api.py, line: 294
#: NEEDS WORK
#, python-brace-format
msgid "Error triggering workflow. Response code: {0}"
msgstr "Chyba při spuštění pracovního postupu. Kód odpovědi: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 297
#: NEEDS WORK
#, python-brace-format
msgid "Build workflow ({0}) triggered successfully."
msgstr "Workflow sestavení ({0}) byl úspěšně spuštěn."
# 
# File: usr/share/build-package/github_api.py, line: 301
#: NEEDS WORK
#, python-brace-format
msgid "URL to monitor the build: {0}"
msgstr "URL pro sledování sestavení: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 305
#: NEEDS WORK
#, python-brace-format
msgid "Error triggering workflow: {0}"
msgstr "Chyba při spuštění pracovního postupu: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 313
#: NEEDS WORK
#, python-brace-format
msgid "Token file '{0}' not found."
msgstr "Soubor tokenu '{0}' nebyl nalezen."
# 
# File: usr/share/build-package/github_api.py, line: 331
#: NEEDS WORK
#, python-brace-format
msgid "Token for organization '{0}' not found."
msgstr "Token pro organizaci '{0}' nebyl nalezen."
# 
# File: usr/share/build-package/github_api.py, line: 334
#: NEEDS WORK
#, python-brace-format
msgid "Error reading token: {0}"
msgstr "Chyba při čtení tokenu: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 345
#: NEEDS WORK
#, python-brace-format
msgid "Cleaning Actions jobs with '{0}' status..."
msgstr "Úklidové akce úloh se stavem '{0}'..."
# 
# File: usr/share/build-package/github_api.py, line: 354
#: NEEDS WORK
#, python-brace-format
msgid "Error fetching Actions jobs. Code: {0}"
msgstr "Chyba při načítání pracovních úloh akcí. Kód: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 361
#: NEEDS WORK
#, python-brace-format
msgid "No Action jobs with '{0}' status found."
msgstr "Nebyly nalezeny žádné úlohy Akce se stavem '{0}'."
# 
# File: usr/share/build-package/github_api.py, line: 368
#: NEEDS WORK
#, python-brace-format
msgid "Deleting job {0}..."
msgstr "Mazání úlohy {0}..."
# 
# File: usr/share/build-package/github_api.py, line: 378
#: NEEDS WORK
#, python-brace-format
msgid "Error deleting job {0}. Code: {1}"
msgstr "Chyba při odstraňování úlohy {0}. Kód: {1}"
# 
# File: usr/share/build-package/github_api.py, line: 380
#: NEEDS WORK
#, python-brace-format
msgid "Deleted {0} Actions jobs with '{1}' status."
msgstr "Smazány {0} úkoly akcí se stavem '{1}'."
# 
# File: usr/share/build-package/github_api.py, line: 383
#: NEEDS WORK
#, python-brace-format
msgid "Error cleaning Actions jobs: {0}"
msgstr "Chyba při čištění úloh akcí: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 394
#: NEEDS WORK
msgid "Getting tag list..."
msgstr "Načítání seznamu tagů..."
# 
# File: usr/share/build-package/github_api.py, line: 403
#: NEEDS WORK
#, python-brace-format
msgid "Error fetching tags. Code: {0}"
msgstr "Chyba při načítání tagů. Kód: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 409
#: NEEDS WORK
msgid "No tags found."
msgstr "Žádné štítky nenalezeny."
# 
# File: usr/share/build-package/github_api.py, line: 416
#: NEEDS WORK
#, python-brace-format
msgid "Deleting tag {0}..."
msgstr "Odstraňuji značku {0}..."
# 
# File: usr/share/build-package/github_api.py, line: 427
#: NEEDS WORK
#, python-brace-format
msgid "Error deleting tag {0}. Code: {1}"
msgstr "Chyba při odstraňování štítku {0}. Kód: {1}"
# 
# File: usr/share/build-package/github_api.py, line: 429
#: NEEDS WORK
#, python-brace-format
msgid "Deleted {0} tags."
msgstr "Smazány {0} štítků."
# 
# File: usr/share/build-package/github_api.py, line: 432
#: NEEDS WORK
#, python-brace-format
msgid "Error cleaning tags: {0}"
msgstr "Chyba při čištění značek: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 439
#: NEEDS WORK
msgid "Source branch name is required to create a pull request"
msgstr "Název zdrojové větve je vyžadován k vytvoření pull requestu."
# 
# File: usr/share/build-package/github_api.py, line: 446
#: NEEDS WORK
#, python-brace-format
msgid "Token length: {0}"
msgstr "Délka tokenu: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 447
#: NEEDS WORK
#, python-brace-format
msgid "Repository name: {0}"
msgstr "Název repozitáře: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 448
#: NEEDS WORK
#, python-brace-format
msgid "Creating PR from '{0}' to '{1}'"
msgstr "Vytváření PR z '{0}' do '{1}'"
# 
# File: usr/share/build-package/github_api.py, line: 449
#: NEEDS WORK
msgid "Repository name could not be determined"
msgstr "Název repozitáře nebylo možné určit"
# 
# File: usr/share/build-package/github_api.py, line: 453
#: NEEDS WORK
#, python-brace-format
msgid "Creating pull request from {0} to {1}..."
msgstr "Vytváření pull requestu z {0} do {1}..."
# 
# File: usr/share/build-package/github_api.py, line: 457
#: NEEDS WORK
#, python-brace-format
msgid "Merge {0} into {1}"
msgstr "Sloučit {0} do {1}"
# 
# File: usr/share/build-package/github_api.py, line: 458
#: NEEDS WORK
msgid "Automated PR created by build_package.py"
msgstr "Automatizovaný PR vytvořený build_package.py"
# 
# File: usr/share/build-package/github_api.py, line: 475
#: NEEDS WORK
#, python-brace-format
msgid "Failed to create PR: {0}"
msgstr "Nepodařilo se vytvořit PR: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 476
#: NEEDS WORK
#, python-brace-format
msgid "API response status: {0}"
msgstr "Stav odpovědi API: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 486
#: NEEDS WORK
#, python-brace-format
msgid "Pull request created successfully: {0}"
msgstr "Pull request byl úspěšně vytvořen: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 491
#: NEEDS WORK
msgid "Attempting to merge pull request automatically..."
msgstr "Pokouším se automaticky sloučit žádost o stažení..."
# 
# File: usr/share/build-package/github_api.py, line: 498
#: NEEDS WORK
msgid "Pull request merged successfully"
msgstr "Žádost o sloučení byla úspěšně sloučena"
# 
# File: usr/share/build-package/github_api.py, line: 501
#: NEEDS WORK
#, python-brace-format
msgid "Pull request created but could not be merged automatically: {0}"
msgstr "Byla vytvořena žádost o sloučení, ale nemohla být automaticky sloučena: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 507
#: NEEDS WORK
#, python-brace-format
msgid "Error creating pull request: {0}"
msgstr "Chyba při vytváření pull requestu: {0}"
# 
# File: usr/share/build-package/main.py, line: 21
#: NEEDS WORK
msgid "Operation cancelled by user."
msgstr "Operace zrušena uživatelem."
# 
# File: usr/share/build-package/main.py, line: 24
#: NEEDS WORK
#, python-brace-format
msgid "Unhandled error: {0}"
msgstr "Nepodložená chyba: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 111
#: NEEDS WORK
#, python-brace-format
msgid "Git has changes: {0} - {1}"
msgstr "Git má změny: {0} - {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 114
#: NEEDS WORK
#, python-brace-format
msgid "Error checking changes: {0}"
msgstr "Chyba při kontrole změn: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 122
# File: usr/share/build-package/git_utils.py, line: 262
# File: usr/share/build-package/git_utils.py, line: 317
#: NEEDS WORK
msgid "This operation is only available in Git repositories."
msgstr "Tato operace je k dispozici pouze v repozitářích Git."
# 
# File: usr/share/build-package/git_utils.py, line: 142
#: NEEDS WORK
#, python-brace-format
msgid "Current branch: {0}"
msgstr "Aktuální větev: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 165
#: NEEDS WORK
#, python-brace-format
msgid "Most recent branch identified: {0}"
msgstr "Nejnovější identifikovaná větev: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 171
#: NEEDS WORK
#, python-brace-format
msgid "Pulling latest changes from most recent branch: {0}"
msgstr "Stahování nejnovějších změn z nejnovější větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 182
# File: usr/share/build-package/git_utils.py, line: 197
#: NEEDS WORK
#, python-brace-format
msgid "Successfully pulled latest changes from {0}"
msgstr "Úspěšně staženy nejnovější změny z {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 188
#: NEEDS WORK
#, python-brace-format
msgid "Failed to pull from {0}, trying current branch: {1}"
msgstr "Nepodařilo se stáhnout z {0}, pokouším se o aktuální větev: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 203
#: NEEDS WORK
msgid "Failed to pull from current branch, trying dev branch"
msgstr "Nepodařilo se stáhnout z aktuální větve, pokouším se o větev dev."
# 
# File: usr/share/build-package/git_utils.py, line: 212
#: NEEDS WORK
msgid "Successfully pulled latest changes from dev"
msgstr "Úspěšně staženy nejnovější změny z vývoje"
# 
# File: usr/share/build-package/git_utils.py, line: 220
#: NEEDS WORK
#, python-brace-format
msgid "Error pulling changes: {0}"
msgstr "Chyba při stahování změn: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 225
#: NEEDS WORK
#, python-brace-format
msgid "Unexpected error: {0}"
msgstr "Neočekávaná chyba: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 255
#: NEEDS WORK
#, python-brace-format
msgid "Error finding most recent branch: {0}"
msgstr "Chyba při hledání nejnovější větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 271
#: NEEDS WORK
#, python-brace-format
msgid "Creating new branch: {0}"
msgstr "Vytváření nové větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 275
#: NEEDS WORK
msgid "Pushing new branch to remote repository..."
msgstr "Odesílání nové větve do vzdáleného repozitáře..."
# 
# File: usr/share/build-package/git_utils.py, line: 278
#: NEEDS WORK
#, python-brace-format
msgid "Branch {0} created and pushed successfully!"
msgstr "Větev {0} byla úspěšně vytvořena a odeslána!"
# 
# File: usr/share/build-package/git_utils.py, line: 281
#: NEEDS WORK
#, python-brace-format
msgid "Error creating or pushing branch: {0}"
msgstr "Chyba při vytváření nebo odesílání větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 322
#: NEEDS WORK
msgid "Getting branch list..."
msgstr "Načítání seznamu větví..."
# 
# File: usr/share/build-package/git_utils.py, line: 368
#: NEEDS WORK
#, python-brace-format
msgid "Keeping only the most recent dev branch: {0}"
msgstr "Udržování pouze nejnovější vývojové větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 373
#: NEEDS WORK
#, python-brace-format
msgid "Removing local branch: {0}"
msgstr "Odstranění místní větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 393
#: NEEDS WORK
#, python-brace-format
msgid "Error removing local branch {0}: {1}"
msgstr "Chyba při odstraňování místní větve {0}: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 398
#: NEEDS WORK
#, python-brace-format
msgid "Removing remote branch: {0}"
msgstr "Odstranění vzdálené větve: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 402
#: NEEDS WORK
#, python-brace-format
msgid "Error removing remote branch {0}: {1}"
msgstr "Chyba při odstraňování vzdálené větve {0}: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 404
#: NEEDS WORK
msgid "Branch cleanup completed successfully!"
msgstr "Údržba větve byla úspěšně dokončena!"
# 
# File: usr/share/build-package/git_utils.py, line: 407
#: NEEDS WORK
#, python-brace-format
msgid "Error during branch cleanup: {0}"
msgstr "Chyba během čištění větve: {0}"
# 
# File: usr/share/build-package/menu_system.py, line: 45
# File: usr/share/build-package/menu_system.py, line: 59
#: NEEDS WORK
msgid "Exit"
msgstr "Konec"
# 
# File: usr/share/build-package/menu_system.py, line: 47
# File: usr/share/build-package/menu_system.py, line: 61
#: NEEDS WORK
msgid "Back"
msgstr "Zpět"
# 
# File: usr/share/build-package/menu_system.py, line: 91
#: NEEDS WORK
msgid "Use [white]arrow keys ↑↓[/] to navigate, [white]Enter[/] to select, [white]ESC[/] to exit"
msgstr ""
"Použijte [white]klávesy se šipkami ↑↓[/] pro navigaci, [white]Enter[/] pro výběr, [white]ESC[/] pro "
"ukončení"
# 
# File: usr/share/build-package/logger.py, line: 67
#: NEEDS WORK
msgid "ERROR"
msgstr "CHYBA"
# 
# File: usr/share/build-package/logger.py, line: 119
#: NEEDS WORK
msgid "Field"
msgstr "Pole"
# 
# File: usr/share/build-package/logger.py, line: 120
#: NEEDS WORK
msgid "Value"
msgstr "Hodnota"
