# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the . package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: .\n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: attranslate\n"
# 
# File: usr/share/build-package/github_api.py, line: 29
# File: usr/share/build-package/github_api.py, line: 73
# File: usr/share/build-package/github_api.py, line: 342
# File: usr/share/build-package/github_api.py, line: 391
#: NEEDS WORK
msgid "Could not determine repository name."
msgstr "Nem sikerült meghatározni a tároló nevét."
# 
# File: usr/share/build-package/github_api.py, line: 35
#: NEEDS WORK
msgid "Could not determine current commit SHA."
msgstr "Nem sikerült meghatározni a jelenlegi commit SHA-t."
# 
# File: usr/share/build-package/github_api.py, line: 44
#: NEEDS WORK
#, python-brace-format
msgid "Creating reference: {0}..."
msgstr "Hivatkozás létrehozása: {0}..."
# 
# File: usr/share/build-package/github_api.py, line: 59
# File: usr/share/build-package/github_api.py, line: 65
#: NEEDS WORK
#, python-brace-format
msgid "Error creating reference: {0}"
msgstr "Hiba a hivatkozás létrehozásakor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 62
#: NEEDS WORK
#, python-brace-format
msgid "Reference {0} created successfully!"
msgstr "A(z) {0} hivatkozás sikeresen létrejött!"
# 
# File: usr/share/build-package/github_api.py, line: 86
#: NEEDS WORK
#, python-brace-format
msgid "Could not determine SHA for {0}."
msgstr "Nem sikerült meghatározni a SHA-t a(z) {0} számára."
# 
# File: usr/share/build-package/github_api.py, line: 89
#: NEEDS WORK
#, python-brace-format
msgid "Creating branch: {0} based on {1}..."
msgstr "Ág létrehozása: {0} a {1} alapján..."
# 
# File: usr/share/build-package/github_api.py, line: 101
# File: usr/share/build-package/github_api.py, line: 166
#: NEEDS WORK
#, python-brace-format
msgid "Error creating branch: {0}"
msgstr "Hiba a ág létrehozásakor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 102
# File: usr/share/build-package/github_api.py, line: 478
#: NEEDS WORK
#, python-brace-format
msgid "Error details: {0}"
msgstr "Hiba részletei: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 160
#: NEEDS WORK
#, python-brace-format
msgid "Warning: Could not mark branch as non-PR: {0}"
msgstr "Figyelmeztetés: Nem sikerült a ágat nem PR-ként megjelölni: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 163
#: NEEDS WORK
#, python-brace-format
msgid "Branch {0} created successfully!"
msgstr "A(z) {0} ág sikeresen létrehozva!"
# 
# File: usr/share/build-package/github_api.py, line: 240
#: NEEDS WORK
msgid "Failed to create branch for the build."
msgstr "A build ághoz nem sikerült ágat létrehozni."
# 
# File: usr/share/build-package/github_api.py, line: 245
#: NEEDS WORK
#, python-brace-format
msgid "Using existing branch: {0}"
msgstr "A meglévő ágazat használata: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 267
#: NEEDS WORK
#, python-brace-format
msgid "Error retrieving remote repository URL for package: {0}"
msgstr "Hiba a távoli tároló URL-jének lekérése a csomaghoz: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 270
#: NEEDS WORK
#, python-brace-format
msgid "Detected repository: {0}"
msgstr "Felfedezett tároló: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 285
#: NEEDS WORK
msgid "Triggering build workflow on GitHub..."
msgstr "A GitHub-on történő build munkafolyamat indítása..."
# 
# File: usr/share/build-package/github_api.py, line: 294
#: NEEDS WORK
#, python-brace-format
msgid "Error triggering workflow. Response code: {0}"
msgstr "Hiba a munkafolyamat aktiválásakor. Válaszkód: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 297
#: NEEDS WORK
#, python-brace-format
msgid "Build workflow ({0}) triggered successfully."
msgstr "A munkafolyamat ({0}) sikeresen elindult."
# 
# File: usr/share/build-package/github_api.py, line: 301
#: NEEDS WORK
#, python-brace-format
msgid "URL to monitor the build: {0}"
msgstr "A build figyeléséhez használt URL: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 305
#: NEEDS WORK
#, python-brace-format
msgid "Error triggering workflow: {0}"
msgstr "Hiba a munkafolyamat aktiválásakor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 313
#: NEEDS WORK
#, python-brace-format
msgid "Token file '{0}' not found."
msgstr "A '{0}' token fájl nem található."
# 
# File: usr/share/build-package/github_api.py, line: 331
#: NEEDS WORK
#, python-brace-format
msgid "Token for organization '{0}' not found."
msgstr "A '{0}' szervezethez tartozó token nem található."
# 
# File: usr/share/build-package/github_api.py, line: 334
#: NEEDS WORK
#, python-brace-format
msgid "Error reading token: {0}"
msgstr "Hiba a token olvasásakor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 345
#: NEEDS WORK
#, python-brace-format
msgid "Cleaning Actions jobs with '{0}' status..."
msgstr "Tisztítási műveletek a '{0}' állapotú feladatokkal..."
# 
# File: usr/share/build-package/github_api.py, line: 354
#: NEEDS WORK
#, python-brace-format
msgid "Error fetching Actions jobs. Code: {0}"
msgstr "Hiba az Actions feladatok lekérésekor. Kód: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 361
#: NEEDS WORK
#, python-brace-format
msgid "No Action jobs with '{0}' status found."
msgstr "Nincs '{0}' állapotú No Action feladat."
# 
# File: usr/share/build-package/github_api.py, line: 368
#: NEEDS WORK
#, python-brace-format
msgid "Deleting job {0}..."
msgstr "Feladat törlése {0}..."
# 
# File: usr/share/build-package/github_api.py, line: 378
#: NEEDS WORK
#, python-brace-format
msgid "Error deleting job {0}. Code: {1}"
msgstr "Hiba a feladat törlésekor: {0}. Kód: {1}"
# 
# File: usr/share/build-package/github_api.py, line: 380
#: NEEDS WORK
#, python-brace-format
msgid "Deleted {0} Actions jobs with '{1}' status."
msgstr "Törölt {0} Akció munkát a '{1}' állapotban."
# 
# File: usr/share/build-package/github_api.py, line: 383
#: NEEDS WORK
#, python-brace-format
msgid "Error cleaning Actions jobs: {0}"
msgstr "Hiba az Actions feladatok tisztításakor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 394
#: NEEDS WORK
msgid "Getting tag list..."
msgstr "Címkék listájának lekérése..."
# 
# File: usr/share/build-package/github_api.py, line: 403
#: NEEDS WORK
#, python-brace-format
msgid "Error fetching tags. Code: {0}"
msgstr "Hiba a címkék lekérésekor. Kód: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 409
#: NEEDS WORK
msgid "No tags found."
msgstr "Nincsenek címkék."
# 
# File: usr/share/build-package/github_api.py, line: 416
#: NEEDS WORK
#, python-brace-format
msgid "Deleting tag {0}..."
msgstr "Címke {0} törlése..."
# 
# File: usr/share/build-package/github_api.py, line: 427
#: NEEDS WORK
#, python-brace-format
msgid "Error deleting tag {0}. Code: {1}"
msgstr "Hiba a címke törlésekor: {0}. Kód: {1}"
# 
# File: usr/share/build-package/github_api.py, line: 429
#: NEEDS WORK
#, python-brace-format
msgid "Deleted {0} tags."
msgstr "Törölt {0} címkét."
# 
# File: usr/share/build-package/github_api.py, line: 432
#: NEEDS WORK
#, python-brace-format
msgid "Error cleaning tags: {0}"
msgstr "Hiba a címkék törlésekor: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 439
#: NEEDS WORK
msgid "Source branch name is required to create a pull request"
msgstr "A forráság neve kötelező a pull request létrehozásához."
# 
# File: usr/share/build-package/github_api.py, line: 446
#: NEEDS WORK
#, python-brace-format
msgid "Token length: {0}"
msgstr "Token hossza: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 447
#: NEEDS WORK
#, python-brace-format
msgid "Repository name: {0}"
msgstr "Tárhely neve: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 448
#: NEEDS WORK
#, python-brace-format
msgid "Creating PR from '{0}' to '{1}'"
msgstr "PR létrehozása a '{0}'-ról a '{1}'-re"
# 
# File: usr/share/build-package/github_api.py, line: 449
#: NEEDS WORK
msgid "Repository name could not be determined"
msgstr "A tároló neve nem határozható meg."
# 
# File: usr/share/build-package/github_api.py, line: 453
#: NEEDS WORK
#, python-brace-format
msgid "Creating pull request from {0} to {1}..."
msgstr "Kérés létrehozása a {0} és {1} között..."
# 
# File: usr/share/build-package/github_api.py, line: 457
#: NEEDS WORK
#, python-brace-format
msgid "Merge {0} into {1}"
msgstr "Egyesítse {0}-t {1}-be"
# 
# File: usr/share/build-package/github_api.py, line: 458
#: NEEDS WORK
msgid "Automated PR created by build_package.py"
msgstr "Automatikus PR létrehozva a build_package.py által"
# 
# File: usr/share/build-package/github_api.py, line: 475
#: NEEDS WORK
#, python-brace-format
msgid "Failed to create PR: {0}"
msgstr "PR létrehozása nem sikerült: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 476
#: NEEDS WORK
#, python-brace-format
msgid "API response status: {0}"
msgstr "API válasz státusz: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 486
#: NEEDS WORK
#, python-brace-format
msgid "Pull request created successfully: {0}"
msgstr "A pull kérés sikeresen létrejött: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 491
#: NEEDS WORK
msgid "Attempting to merge pull request automatically..."
msgstr "Próbálkozás a pull request automatikus egyesítésével..."
# 
# File: usr/share/build-package/github_api.py, line: 498
#: NEEDS WORK
msgid "Pull request merged successfully"
msgstr "A pull request sikeresen egyesítve."
# 
# File: usr/share/build-package/github_api.py, line: 501
#: NEEDS WORK
#, python-brace-format
msgid "Pull request created but could not be merged automatically: {0}"
msgstr "Pull kérés létrehozva, de nem lehetett automatikusan egyesíteni: {0}"
# 
# File: usr/share/build-package/github_api.py, line: 507
#: NEEDS WORK
#, python-brace-format
msgid "Error creating pull request: {0}"
msgstr "Hiba a pull request létrehozásakor: {0}"
# 
# File: usr/share/build-package/main.py, line: 21
#: NEEDS WORK
msgid "Operation cancelled by user."
msgstr "Műveletet a felhasználó megszakította."
# 
# File: usr/share/build-package/main.py, line: 24
#: NEEDS WORK
#, python-brace-format
msgid "Unhandled error: {0}"
msgstr "Kezelhetetlen hiba: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 111
#: NEEDS WORK
#, python-brace-format
msgid "Git has changes: {0} - {1}"
msgstr "A Git változásai: {0} - {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 114
#: NEEDS WORK
#, python-brace-format
msgid "Error checking changes: {0}"
msgstr "Hiba a változtatások ellenőrzésekor: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 122
# File: usr/share/build-package/git_utils.py, line: 262
# File: usr/share/build-package/git_utils.py, line: 317
#: NEEDS WORK
msgid "This operation is only available in Git repositories."
msgstr "Ez a művelet csak Git tárolókban érhető el."
# 
# File: usr/share/build-package/git_utils.py, line: 142
#: NEEDS WORK
#, python-brace-format
msgid "Current branch: {0}"
msgstr "Aktuális ág: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 165
#: NEEDS WORK
#, python-brace-format
msgid "Most recent branch identified: {0}"
msgstr "Legutóbbi azonosított ág: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 171
#: NEEDS WORK
#, python-brace-format
msgid "Pulling latest changes from most recent branch: {0}"
msgstr "A legfrissebb változtatások letöltése a legutolsó ágból: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 182
# File: usr/share/build-package/git_utils.py, line: 197
#: NEEDS WORK
#, python-brace-format
msgid "Successfully pulled latest changes from {0}"
msgstr "Sikeresen letöltötte a legújabb változtatásokat a {0} -tól."
# 
# File: usr/share/build-package/git_utils.py, line: 188
#: NEEDS WORK
#, python-brace-format
msgid "Failed to pull from {0}, trying current branch: {1}"
msgstr "Sikertelen a {0} letöltése, próbálkozás a jelenlegi ággal: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 203
#: NEEDS WORK
msgid "Failed to pull from current branch, trying dev branch"
msgstr "Sikertelen a jelenlegi ágból való letöltés, próbálkozás a fejlesztői ággal"
# 
# File: usr/share/build-package/git_utils.py, line: 212
#: NEEDS WORK
msgid "Successfully pulled latest changes from dev"
msgstr "Sikeresen letöltötte a legújabb változtatásokat a dev-ből."
# 
# File: usr/share/build-package/git_utils.py, line: 220
#: NEEDS WORK
#, python-brace-format
msgid "Error pulling changes: {0}"
msgstr "Hiba a változtatások letöltésekor: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 225
#: NEEDS WORK
#, python-brace-format
msgid "Unexpected error: {0}"
msgstr "Váratlan hiba: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 255
#: NEEDS WORK
#, python-brace-format
msgid "Error finding most recent branch: {0}"
msgstr "Hiba a legfrissebb ág keresésekor: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 271
#: NEEDS WORK
#, python-brace-format
msgid "Creating new branch: {0}"
msgstr "Új ág létrehozása: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 275
#: NEEDS WORK
msgid "Pushing new branch to remote repository..."
msgstr "Új ág feltöltése a távoli tárolóra..."
# 
# File: usr/share/build-package/git_utils.py, line: 278
#: NEEDS WORK
#, python-brace-format
msgid "Branch {0} created and pushed successfully!"
msgstr "A(z) {0} ág sikeresen létrehozva és feltöltve!"
# 
# File: usr/share/build-package/git_utils.py, line: 281
#: NEEDS WORK
#, python-brace-format
msgid "Error creating or pushing branch: {0}"
msgstr "Hiba a ág létrehozásakor vagy feltöltésekor: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 322
#: NEEDS WORK
msgid "Getting branch list..."
msgstr "Áglista lekérése..."
# 
# File: usr/share/build-package/git_utils.py, line: 368
#: NEEDS WORK
#, python-brace-format
msgid "Keeping only the most recent dev branch: {0}"
msgstr "Csak a legfrissebb fejlesztői ágat tartva: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 373
#: NEEDS WORK
#, python-brace-format
msgid "Removing local branch: {0}"
msgstr "Helyi ág eltávolítása: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 393
#: NEEDS WORK
#, python-brace-format
msgid "Error removing local branch {0}: {1}"
msgstr "Hiba a helyi ág eltávolításakor {0}: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 398
#: NEEDS WORK
#, python-brace-format
msgid "Removing remote branch: {0}"
msgstr "Távoli ág eltávolítása: {0}"
# 
# File: usr/share/build-package/git_utils.py, line: 402
#: NEEDS WORK
#, python-brace-format
msgid "Error removing remote branch {0}: {1}"
msgstr "Hiba a távoli ág eltávolításakor {0}: {1}"
# 
# File: usr/share/build-package/git_utils.py, line: 404
#: NEEDS WORK
msgid "Branch cleanup completed successfully!"
msgstr "A ág tisztítása sikeresen befejeződött!"
# 
# File: usr/share/build-package/git_utils.py, line: 407
#: NEEDS WORK
#, python-brace-format
msgid "Error during branch cleanup: {0}"
msgstr "Hiba a ág tisztítása során: {0}"
# 
# File: usr/share/build-package/menu_system.py, line: 45
# File: usr/share/build-package/menu_system.py, line: 59
#: NEEDS WORK
msgid "Exit"
msgstr "Kilépés"
# 
# File: usr/share/build-package/menu_system.py, line: 47
# File: usr/share/build-package/menu_system.py, line: 61
#: NEEDS WORK
msgid "Back"
msgstr "Vissza"
# 
# File: usr/share/build-package/menu_system.py, line: 91
#: NEEDS WORK
msgid "Use [white]arrow keys ↑↓[/] to navigate, [white]Enter[/] to select, [white]ESC[/] to exit"
msgstr ""
"Használja a [fehér]nyíl billentyűket ↑↓[/] a navigáláshoz, [fehér]Enter[/] a kiválasztáshoz, "
"[fehér]ESC[/] a kilépéshez."
# 
# File: usr/share/build-package/logger.py, line: 67
#: NEEDS WORK
msgid "ERROR"
msgstr "HIBA"
# 
# File: usr/share/build-package/logger.py, line: 119
#: NEEDS WORK
msgid "Field"
msgstr "Mező"
# 
# File: usr/share/build-package/logger.py, line: 120
#: NEEDS WORK
msgid "Value"
msgstr "Érték"
